document.write('<footer>')
document.write('  <div class="container">')
document.write('    <div class="row">')
document.write('      <div class="col-lg-8 col-md-10 mx-auto">')
document.write('        <ul class="list-inline text-center">')
document.write('          <li class="list-inline-item">')
document.write('            <a href="#">')
document.write('              <span class="fa-stack fa-lg">')
document.write('                <i class="fa fa-circle fa-stack-2x"></i>')
document.write('                <i class="fa fa-twitter fa-stack-1x fa-inverse"></i>')
document.write('              </span>')
document.write('            </a>')
document.write('          </li>')
document.write('          <li class="list-inline-item">')
document.write('            <a href="#">')
document.write('              <span class="fa-stack fa-lg">')
document.write('                <i class="fa fa-circle fa-stack-2x"></i>')
document.write('                <i class="fa fa-facebook fa-stack-1x fa-inverse"></i>')
document.write('              </span>')
document.write('            </a>')
document.write('          </li>')
document.write('          <li class="list-inline-item">')
document.write('            <a href="https://github.com/svihra/TimepixCamWeb">')
document.write('              <span class="fa-stack fa-lg">')
document.write('                <i class="fa fa-circle fa-stack-2x"></i>')
document.write('                <i class="fa fa-github fa-stack-1x fa-inverse"></i>')
document.write('              </span>')
document.write('            </a>')
document.write('          </li>')
document.write('        </ul>')
document.write('        <p class="copyright text-muted">Copyright &copy; Your Website 2017</p>')
document.write('      </div>')
document.write('    </div>')
document.write('  </div>')
document.write('</footer>')
