document.write('<nav class="navbar navbar-expand-lg navbar-light fixed-top" id="mainNav">')
document.write('  <div class="container">')
document.write('    <a class="navbar-brand" href="/detektor/index.html">TimepixCam</a>')
document.write('    <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarResponsive" aria-controls="navbarResponsive" aria-expanded="false" aria-label="Toggle navigation">')
document.write('      Menu')
document.write('      <i class="fa fa-bars"></i>')
document.write('    </button>')
document.write('    <div class="collapse navbar-collapse" id="navbarResponsive">')
document.write('      <ul class="navbar-nav ml-auto">')
document.write('        <li class="nav-item">')
document.write('          <a class="nav-link" href="/detektor/index.html">Home</a>')
document.write('        </li>')
document.write('        <li class="nav-item">')
document.write('          <a class="nav-link" href="/detektor/about.html">About</a>')
document.write('        </li>')
document.write('        <li class="nav-item dropdown">')
document.write('          <a class="nav-link" href="/detektor/applications.html" id="navbarDropdownMenuLink" aria-haspopup="true" aria-expanded="false">')
document.write('            Applications')
document.write('          </a>')
document.write('          <div class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">')
document.write('            <a class="dropdown-item" href="/detektor/applications/application1.html">Time Stamping</a>')
document.write('            <a class="dropdown-item" href="/detektor/applications/application1.html">Light Sources</a>')
document.write('            <a class="dropdown-item" href="/detektor/applications/application1.html">Single Photon Detection</a>')
document.write('            <a class="dropdown-item" href="/detektor/applications/application1.html">Ion Imaging</a>')
document.write('          </div>')
document.write('        </li>')
document.write('        <li class="nav-item">')
document.write('          <a class="nav-link" href="/detektor/collaboration.html">Collaboration</a>')
document.write('        </li>')
document.write('        <li class="nav-item">')
document.write('          <a class="nav-link" href="/detektor/publications.html">Publications</a>')
document.write('        </li>')
document.write('        <li class="nav-item">')
document.write('          <a class="nav-link" href="/detektor/contact.html">Contact Us</a>')
document.write('        </li>')
document.write('      </ul>')
document.write('    </div>')
document.write('  </div>')
document.write('</nav>')
